### ISSUE TITLE
agdktunnel doesn't build with androidx.games:games-activity:1.2.2

### ISSUE THREAD

**Issue by todi1856** [android/games-samples#26]
Bump game activity package version in games-samples\agdk\agdktunnel\app\build.gradle to androidx.games:games-activity:1.2.2, try to build, you'll get errors like:

```
Cause: error when building with cmake using E:\Projects\AndroidSamples\games-samples\agdk\agdktunnel\app\src\main\cpp\CMakeLists.txt: Build command failed.
Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi armeabi-v7a --os-version 24 --stl c++_shared --ndk-version 23 --output E:\Projects\AndroidSamples\games-samples\agdk\agdktunnel\app\.cxx\cmake\mobileDebug\prefab\armeabi-v7a\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\2f6a1e59057ecdc47c6b0e818e2d9875\oboe-1.5.0\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\e00d2db2c311ec7364fd5f1263ccbab4\games-frame-pacing-1.10.0\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\edb5a03260ce2909a9d633dba5f6ef0e\games-performance-tuner-1.5.0\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\c140fbfa8c469b36c59fada99110bf82\games-activity-1.2.2\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\7c36ebcb07a241d4a4517b97d4c141a3\games-controller-1.1.0\prefab C:\Users\tomas\.gradle\caches\transforms-2\files-2.1\23bffa59942037505e750e653afa3acd\games-memory-advice-1.0.0-beta03\prefab}

Exception in thread "main" java.lang.IllegalArgumentException: Only schema_version 1 is supported. game-activity uses version 2.
	at com.google.prefab.api.Package.<init>(Package.kt:46)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:124)
	at com.google.prefab.cli.Cli$packages$2.invoke(Cli.kt:95)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.prefab.cli.Cli.getPackages(Cli.kt)
	at com.google.prefab.cli.Cli.validate(Cli.kt:172)
	at com.google.prefab.cli.Cli.run(Cli.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:168)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at com.google.prefab.cli.AppKt.main(App.kt:28)

```

Using Android Studio 2021.3.1 if it matters

**Comment by natetrost** [comment]
There is a PR pending to update the sample to 1.2.2, but it is waiting on an updated release of the Game Controller library for compatibility with GameActivity 1.2.

There are a few changes required to build with GameActivity 1.2.2:

* Changing the prefab version in `gradle.properties` to `android.prefabVersion=2.0.0`
* Updating the version in `gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip`
* Updating the AGP version in the root `build.gradle` to `classpath 'com.android.tools.build:gradle:7.2.1'`
* Updating `CMakeLists.txt`, adding `game-activity::game-activity_static` to the list of included libraries and removing the `game_activity_included.cpp`, `game_text_input_included.cpp` and `native_app_glue_included.c` files from the list of included source code files.

**Comment by natetrost** [comment]
Fixed by https://github.com/android/games-samples/pull/30
